FROM php:7.3.27-fpm-alpine3.13

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN   install-php-extensions yaf redis  rdkafka mongodb  PDO  pdo_mysql gd curl swoole xdebug