FROM php:5.6-fpm-alpine

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN   install-php-extensions redis  rdkafka mongodb  PDO  pdo_mysql gd curl swoole xdebug

